package:
    name: metos3d
    version: 0.0.0

source:
   git_url: https://github.com/jpicau/metos3d.git
#   git_tag: n2.2.4

build:
    number: 0

#requirements:
#    build:
#        - x264 # [unix]
#        - openssl
#        - yasm # [unix]
#        - mingw # [win]
#    run:
#        - x264 # [unix]
#        - openssl

about:
    home: http://metos3d.github.io/
    license: GPL-3
