
package:
    name:       m3d
    version:    "0.0.0"

source:
    path: .

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - mpi 1.0 openmpi
        - python
    host:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - mpi 1.0 openmpi
        - python
    run:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - mpi 1.0 openmpi
        - python

